[2025-05-07T21:20:49.312+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-07T21:20:49.331+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: dags_python_with_macro.task_using_macros scheduled__2025-05-06T15:10:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-05-07T21:20:49.785+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2025-05-07T21:20:54.712+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-07T21:20:54.727+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: dags_python_with_macro.task_using_macros scheduled__2025-05-06T15:10:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-05-07T21:20:54.738+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
